name: Lean Action CI

on:
  push:
  pull_request:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
        - name: Linux-x86_64
          os: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install BLAS/Linux
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y libopenblas-dev

    - name: Set up Lean
      uses: leanprover/lean-action@v1
      with:
        auto-config: false
        use-github-cache: false

    - name: Build project
      run: lake build

    - name: Build site
      run: lake exe sclean --depth 2 --output _out/

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        # Upload entire repository
        path: '.'

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_out/html-multi/
